"""
TrendAI Analysis Agent
Generates professional, non-technical explanations for investors
"""

class AnalysisAgent:
    """
    Intelligent agent that translates technical risk data into
    clear, actionable insights for crypto investors.
    """

    def generate_token_analysis(self, token_data: dict, narratives: list, suspicious_posts: list) -> dict:
        """
        Creates a comprehensive, easy-to-understand analysis report

        Args:
            token_data: Risk profile from database
            narratives: Active narratives list
            suspicious_posts: Sample of suspicious posts

        Returns:
            Dictionary with explanation, findings, and recommendations
        """
        token_id = token_data.get('token_id', 'UNKNOWN')
        risk_score = token_data.get('risk_score', 0)
        risk_label = token_data.get('risk_label', 'SAFE')
        bot_ratio = token_data.get('bot_ratio', 0)
        avg_sentiment = token_data.get('avg_sentiment', 0)

        # Generate main explanation
        explanation = self._generate_explanation(
            risk_label, risk_score, bot_ratio, avg_sentiment
        )

        # Extract key findings
        key_findings = self._extract_key_findings(
            token_data, narratives, suspicious_posts
        )

        # Generate recommendations
        recommendations = self._generate_recommendations(
            risk_label, risk_score, bot_ratio, narratives
        )

        return {
            'token_id': token_id,
            'risk_score': risk_score,
            'risk_label': risk_label,
            'explanation': explanation,
            'key_findings': key_findings,
            'recommendations': recommendations,
            'confidence': self._calculate_confidence(token_data)
        }

    def _generate_explanation(self, risk_label: str, risk_score: float,
                             bot_ratio: float, avg_sentiment: float) -> str:
        """Generate main explanation in plain language"""

        if risk_label == "PUMP & DUMP":
            return (
                f"Our AI system has detected strong signs of artificial price manipulation. "
                f"Analysis shows that {bot_ratio:.1f}% of the online conversation appears to be "
                f"generated by automated accounts, not real people. These accounts are spreading "
                f"unusually positive messages to create artificial excitement. This pattern is "
                f"commonly seen before a 'pump and dump' scheme, where prices are artificially "
                f"inflated before orchestrators sell their holdings."
            )

        elif risk_label == "FUD ATTACK":
            return (
                f"We've identified a coordinated negative campaign targeting this token. "
                f"Approximately {bot_ratio:.1f}% of recent posts appear to come from automated "
                f"accounts spreading fear, uncertainty, and doubt (FUD). This could be an attempt "
                f"to drive the price down artificially, possibly by competitors or short-sellers. "
                f"While some criticism may be legitimate, the coordinated nature suggests manipulation."
            )

        elif risk_label == "HIGH RISK":
            return (
                f"This token shows significant warning signs that should concern investors. "
                f"Our analysis found that {bot_ratio:.1f}% of the online discussion is likely "
                f"not genuine community engagement. This high level of inorganic activity suggests "
                f"someone is trying to manipulate public perception. Real, healthy projects typically "
                f"have much more authentic community discussions."
            )

        elif risk_label == "SUSPICIOUS":
            return (
                f"While not definitively dangerous, this token shows some concerning patterns. "
                f"About {bot_ratio:.1f}% of the conversation appears inorganic, which is higher "
                f"than what we see with established, legitimate projects. This doesn't necessarily "
                f"mean it's a scam, but it suggests you should do extra research before investing."
            )

        else:  # SAFE
            return (
                f"Based on our analysis, this token's online community appears largely genuine. "
                f"Only {bot_ratio:.1f}% of posts show signs of automation, which is within normal "
                f"ranges for crypto projects. The conversations seem to reflect real people discussing "
                f"the project naturally. However, always do your own research before investing."
            )

    def _extract_key_findings(self, token_data: dict, narratives: list,
                             suspicious_posts: list) -> list:
        """Extract bullet-point findings"""
        findings = []

        bot_ratio = token_data.get('bot_ratio', 0)
        total_posts = token_data.get('total_posts', 0)
        avg_sentiment = token_data.get('avg_sentiment', 0)

        # Finding 1: Volume analysis
        if total_posts > 100:
            findings.append({
                'category': 'Volume',
                'finding': f"Analyzed {total_posts} posts across social media",
                'severity': 'info'
            })

        # Finding 2: Bot activity
        if bot_ratio > 50:
            findings.append({
                'category': 'Bot Activity',
                'finding': f"Critical: {bot_ratio:.1f}% automated account activity detected",
                'severity': 'critical'
            })
        elif bot_ratio > 30:
            findings.append({
                'category': 'Bot Activity',
                'finding': f"Warning: {bot_ratio:.1f}% of posts appear inorganic",
                'severity': 'warning'
            })
        else:
            findings.append({
                'category': 'Bot Activity',
                'finding': f"Low bot activity: {bot_ratio:.1f}% automated content",
                'severity': 'good'
            })

        # Finding 3: Sentiment analysis
        if avg_sentiment > 0.6:
            findings.append({
                'category': 'Sentiment',
                'finding': "Extremely positive messaging (potential hype campaign)",
                'severity': 'warning'
            })
        elif avg_sentiment < -0.6:
            findings.append({
                'category': 'Sentiment',
                'finding': "Highly negative messaging (potential FUD attack)",
                'severity': 'warning'
            })
        else:
            findings.append({
                'category': 'Sentiment',
                'finding': "Balanced sentiment in community discussions",
                'severity': 'good'
            })

        # Finding 4: Narrative analysis
        if narratives:
            high_risk_narratives = [n for n in narratives if n.get('risk_level') in ['HIGH', 'CRITICAL']]
            if high_risk_narratives:
                findings.append({
                    'category': 'Narratives',
                    'finding': f"Found {len(high_risk_narratives)} manipulated discussion topics",
                    'severity': 'critical'
                })
            else:
                findings.append({
                    'category': 'Narratives',
                    'finding': f"Tracking {len(narratives)} organic discussion topics",
                    'severity': 'info'
                })

        # Finding 5: Suspicious posts
        if suspicious_posts and len(suspicious_posts) > 0:
            findings.append({
                'category': 'Evidence',
                'finding': f"Identified specific suspicious posts for review",
                'severity': 'info'
            })

        return findings

    def _generate_recommendations(self, risk_label: str, risk_score: float,
                                  bot_ratio: float, narratives: list) -> str:
        """Generate actionable recommendations"""

        if risk_label == "PUMP & DUMP":
            return (
                "STRONG CAUTION ADVISED: Avoid investing in this token at current prices. "
                "If you already hold this token, consider taking profits soon. The artificial "
                "hype will likely disappear suddenly, causing rapid price decline. Wait for "
                "legitimate community growth before reconsidering."
            )

        elif risk_label == "FUD ATTACK":
            return (
                "PROCEED WITH CAREFUL ANALYSIS: Don't panic sell based on coordinated negativity, "
                "but don't ignore all criticism either. Research the project's fundamentals independently. "
                "Check if the team is addressing concerns transparently. If fundamentals are solid, "
                "this could be a buying opportunity created by manipulation."
            )

        elif risk_label == "HIGH RISK":
            return (
                "HIGH RISK - EXERCISE EXTREME CAUTION: Do not invest without extensive research. "
                "Look for red flags like anonymous teams, unrealistic promises, or pressure to "
                "buy quickly. If you're already invested, review your position carefully. "
                "The level of manipulation detected is concerning."
            )

        elif risk_label == "SUSPICIOUS":
            return (
                "PROCEED WITH CAUTION: This token requires extra due diligence. Verify the team's "
                "identity and track record. Check if the project solves a real problem. Look for "
                "independent reviews and audits. Only invest amounts you can afford to lose. "
                "Consider waiting for more organic community growth."
            )

        else:  # SAFE
            return (
                "APPEARS RELATIVELY SAFE: While our analysis shows mostly organic activity, "
                "remember that no investment is without risk. Still verify the project fundamentals, "
                "team credentials, and tokenomics. Diversify your portfolio and never invest more "
                "than you can afford to lose. Stay updated on project developments."
            )

    def _calculate_confidence(self, token_data: dict) -> str:
        """Calculate confidence level in the analysis"""
        total_posts = token_data.get('total_posts', 0)

        if total_posts >= 500:
            return "HIGH"
        elif total_posts >= 100:
            return "MEDIUM"
        else:
            return "LOW"

    def generate_quick_check(self, text: str, is_bot: bool, bot_prob: float,
                           sentiment: str, sentiment_score: float) -> dict:
        """
        Generate quick analysis for a single post

        Returns plain-language explanation
        """

        if is_bot and sentiment == "Positive":
            explanation = (
                "This post shows strong signs of being automated or part of a coordinated "
                "campaign. The overly positive language combined with bot-like patterns suggests "
                "it may be trying to create artificial hype. Be skeptical of investment advice "
                "from sources like this."
            )
            verdict = "LIKELY MANIPULATION"

        elif is_bot and sentiment == "Negative":
            explanation = (
                "This appears to be part of a coordinated negative campaign (FUD). While some "
                "criticism may be valid, the bot-like characteristics suggest it's designed to "
                "spread fear rather than provide legitimate analysis. Verify claims independently."
            )
            verdict = "LIKELY FUD"

        elif is_bot:
            explanation = (
                "This post exhibits characteristics common to automated accounts or coordinated "
                "campaigns. It may not represent genuine community sentiment. Treat information "
                "from this source with caution."
            )
            verdict = "SUSPICIOUS"

        else:
            explanation = (
                "This post appears to be from a genuine person rather than an automated account. "
                "However, always verify claims independently and don't make investment decisions "
                "based on single sources."
            )
            verdict = "APPEARS GENUINE"

        return {
            'verdict': verdict,
            'explanation': explanation,
            'bot_probability': round(bot_prob * 100, 1),
            'sentiment': sentiment,
            'confidence': "HIGH" if bot_prob > 0.8 or bot_prob < 0.2 else "MEDIUM"
        }
